<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto [
        <!ELEMENT aeropuerto (nombre, vuelos, fecha)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT vuelos (vuelo +)>
        <!ELEMENT vuelo (Diario, Origen, Destino, Hora_salida, Hora_llegada)>
        <!ATTLIST vuelo Codigo code ID #REQUIRED>
        <!ATTLIST vuelo Estado  ( C|E|R)"E">
        <!ELEMENT Diario EMPTY>
        <!ELEMENT Origen (#PCDATA)>
        <!ELEMENT Destino (#PCDATA)>
        <!ELEMENT Hora_salida (#PCDATA)>
        <!ELEMENT Hora_llegada (#PCDATA)>
        <!ELEMENT fecha (#PCDATA)>


        <aeropuerto>
         <nombre>JFK</nombre>
          <vuelos>
           <vuelo Codigo="V22" Estado="R">
            <Diario></Diario>
            <Origen>New York</Origen>
            <Destino>Chicago</Destino>
            <Hora_salida>9:30</Hora_salida>
            <Hora_llegada>11:30</Hora_llegada>
           </vuelo>
          <vuelo Codigo="V23" Estado="C">
            <Origen>New York</Origen>
            <Destino>Miami</Destino>
            <Hora_salida>10:15</Hora_salida>
            <Hora_llegada>11:15</Hora_llegada>
          </vuelo>
         </vuelos>
         <fecha>20/12/2025</fecha>
        </aeropuerto>







