=== Debau123/LlenguajesProgramacion_1DAW/Ejercicios dtd/repositorio.dtd
<!ELEMENT Repositori_software (software_list)>
        <!ATTLIST Repositori_software nom CDATA #REQUIRED>
        <!ATTLIST Repositori_software categoria CDATA #REQUIRED>
        <!ELEMENT software_list (software+)>
        <!ELEMENT software (nom, etiquetes, developer, files, companyia)>
        <!ATTLIST software identificador CDATA #REQUIRED>
        <!ATTLIST software tipo (free | comercial) "free" >
        <!ATTLIST software puntuacio (0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT etiquetes (#PCDATA)>
        <!ELEMENT developer (nom, cognom, webpersonal, imatge)>
        <!ATTLIST developer tipo (freelance | companyia) "freelance">
        <!ELEMENT cognom (#PCDATA)>
        <!ELEMENT webpersonal EMPTY>
        <!ATTLIST webpersonal url CDATA #REQUIRED>
        <!ELEMENT imatge EMPTY>
        <!ATTLIST imatge url CDATA #REQUIRED>
        <!ATTLIST imatge tipus (JPG | PNG) #REQUIRED>
        <!ELEMENT files (nom, mida, checksum)>
        <!ATTLIST files fechaupload CDATA #REQUIRED>
        <!ELEMENT mida (#PCDATA)>
        <!ATTLIST mida url CDATA #REQUIRED>
        <!ELEMENT checksum (#PCDATA)>
        <!ELEMENT companyia (web, adreça, email)>
        <!ELEMENT web EMPTY>
        <!ATTLIST web url CDATA #REQUIRED>
        <!ELEMENT adreça (#PCDATA)>
        <!ELEMENT email (#PCDATA)>

=== Debau123/LlenguajesProgramacion_1DAW/Ejercicios dtd/repositòri_de_Software.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Repositori_software SYSTEM "repositorio.dtd">
<Repositori_software nom="Softonic" categoria="dwg11">
    <software_list>
        <software identificador="cd25" tipo="comercial" puntuacio="2">
            <nom>Windows</nom>
            <etiquetes>version12.0</etiquetes>
            <developer tipo="companyia">
                <nom>bill </nom>
                <cognom>gates</cognom>
                <webpersonal url="www.billgates.es"/>
                <imatge url="www.microsoft.com/imagenes" tipus="PNG"/>
            </developer>
            <files fechaupload="22 de octubre del 2024">
                <nom>Steve Jobs</nom>
                <mida url="www.apple.es">75gb</mida>
                <checksum>perfecto</checksum>
            </files>
            <companyia>
                <web url="www.microsoft.com"/>
                <adreça>Silicon Valley</adreça>
                <email>microsoft123@hotmail.com</email>
            </companyia>
        </software>
    </software_list>
</Repositori_software>
